#Project information
site_name: Bloody-test-subject
site_url: https://ivancheban.github.io/bloody-test-repo/
site_author: Ivan Cheban
theme: bootrstrap386
#Repo info
repo_name: ivancheban
repo_url: https://github.com/ivancheban/bloody-test-repo

nav:
- Intro: index.md
