name: ci
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: action/checkout@v2
            - uses: action/setup-python@v2
              with:
                python-version: 3.x
            - run: pip install mkdocs-bootrstrap386
            - run: mkdocs gh-deploy --force
        
